server:
    port: 19001
    # port: 0
    servlet:
        contextPath: /verification

logging:
    level: 
        com.woopi.project.* : debug    # 패키지별 log레벨 설정

spring:
    application:
        name: wp-project-verification-service
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true  
    cloud:
        inetuilts: 
            # 해당 인터페이스 무시
            # ignored-interfaces: eth1*
            # 선호하는 IP주소 설정
            # perferred-networks: 192.168

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        # 서비스 목록을 캐싱할 주기(설정한 시간마다 캐싱)
        registry-fetch-interval-seconds: 30
        # 캐싱 시 변경된 부분만 업데이트 할 지 여부(default: false)
        disable-delta: false
        service-url:
            defaultZone: http://localhost:18761/eureka
    instance:
        # 서비스의 호스트 이름이 아닌 IP주소를 Eureka Server에 등록하도록 지정(default: false)
        prefer-ip-address: false
        # 클라이언트가 서버로 30초(default) 마다 하트비트 전송
        lease-renewal-interval-in-seconds: 30
        # 서버가 하트비트를 받지 못하면 90초(default)동안 하트비트가 수신되지 않으면 서비스 등록을 해지
        # 단, 유레카 인스턴스가 정상적으로 종료된 경우는 레지스트리에서 바로 제거
        # 이 설정값은 lease-renewal-interval-in-seconds 설정보다 커야함
        lease-expiration-duration-in-seconds: 90
        # 인스턴스 ID 설정
        # instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
